# packages:
#   - 'packages/*'
packages:
  - 'apps/*'
  - 'libs/**'
allowBuilds:
  '@prisma/client': true
  '@prisma/engines': true
  '@swc/core': false
  bcrypt: true
  nx: false
  prisma: true
  sharp: false
